sonar.projectKey=userService
sonar.projectName=userService
sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=**/repository/**
